name: Lighthouse Badger

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

env:
  URLS: "https://vaibhavkubic-ui.github.io/Vaibhav_Bajpai/"
  REPO_BRANCH: "main"

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          # Use GITHUB_TOKEN to avoid manual PAT management
          token: ${{ secrets.LIGHTHOUSE_BADGER_TOKEN }}

      - name: Run Lighthouse Badger 🚀
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          token: ${{ secrets.LIGHTHOUSE_BADGER_TOKEN }}
          urls: ${{ env.URLS }}
          repo_branch: ${{ env.REPO_BRANCH }}

      - name: Nesting Badges 📂
        uses: actions/checkout@v4
        with:
          repository: "myactionway/lighthouse-badges"
          path: temp_lighthouse_badges_nested
          token: ${{ secrets.GITHUB_TOKEN }}
